// lib/team-logos.ts
export const TEAM_LOGOS: Record<string, string> = {
  Arsenal: "https://crests.football-data.org/57.png",
  "Aston Villa": "https://crests.football-data.org/58.png",
  Bournemouth: "https://crests.football-data.org/1044.png",
  Brentford: "https://crests.football-data.org/402.png",
  "Brighton & Hove Albion": "https://crests.football-data.org/397.png",
  Burnley: "https://crests.football-data.org/328.png",
  Chelsea: "https://crests.football-data.org/61.png",
  "Crystal Palace": "https://crests.football-data.org/354.png",
  Everton: "https://crests.football-data.org/62.png",
  Fulham: "https://crests.football-data.org/63.png",
  "Ipswich Town": "https://crests.football-data.org/349.png",
  "Leeds United": "https://crests.football-data.org/341.png",
  "Leicester City": "https://crests.football-data.org/338.png",
  Liverpool: "https://crests.football-data.org/64.png",
  "Manchester City": "https://crests.football-data.org/65.png",
  "Manchester United": "https://crests.football-data.org/66.png",
  "Newcastle United": "https://crests.football-data.org/67.png",
  "Nottingham Forest": "https://crests.football-data.org/351.png",
  Southampton: "https://crests.football-data.org/340.png",
  "Tottenham Hotspur": "https://crests.football-data.org/73.png",
  "West Ham United": "https://crests.football-data.org/563.png",
  "Wolverhampton Wanderers": "https://crests.football-data.org/76.png",
};
