import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { NextAuthProvider } from "@/server/provider/session-provider";
import Providers from "@/server/provider/query-provider";
import { AppProvider } from "@/server/provider/app-provider";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable} antialiased`}>
        <NextAuthProvider>
          <Providers>
            <AppProvider>{children}</AppProvider>
          </Providers>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
